### ISSUE TITLE
Multiple discord webhooks

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [Qolors/FeedCord#7]
Hi there, I'm wondering if it's possible to setup multiple configs for a single instance?

Currently I'm running 1 instance per webhook, but I'd love if it I could do something like:
```
{
  "RssURLS": [
    "<feed1>",
	"<feed2>"
  ],
  "YoutubeUrls": [""],
  "DiscordWebhookUrl": "<webhook1>,
  "RssCheckIntervalMinutes": 10,
  "AuthorName": "Feedcord"
},
{
  "RssURLS": [
    "<feed1>",
    "<feed3>"
  ],
  "YoutubeUrls": [""],
  "DiscordWebhookUrl": "<webhook2>",
  "RssCheckIntervalMinutes": 10,
  "AuthorName": "Other FeedCord"
}
```

**Comment by Qolors** [comment]
Sorry for the late reply as I was on vacation!

I do something similar where I have an instance per webhook using docker compose. To me it makes sense this way since we're separating the processes.. May I ask why you want it to be ran in one instance? Just curious to hear the reasoning.. Is it performance? Easier management?

I can look in to this when I get settled back in - thanks!

**Comment by LilDrunkenSmurf** [comment]
I'm running it in a kubernetes cluster. Less pods = less resources.

**Comment by Qolors** [comment]
Right on - I'll tag this as feature request and see what I can do. Thanks for the info!

**Comment by Qolors** [comment]
Hey there! Multiple webhook support is now here in the latest [2.0.0 release](https://github.com/Qolors/FeedCord/tree/v2.0.0)

Appreciate the patience and support - cheers!

**Comment by LilDrunkenSmurf** [comment]
Thanks so much!
