### ISSUE TITLE
Feature Request: Only send NEW posts

### ISSUE THREAD

**Issue by Zottelchen** [Qolors/FeedCord#9]
Since RSS can contain arbitrary time data for each post, I would love to have a toggle to only allow new posts. Best example would be https://lowendtalk.com/categories/offers/feed.rss - each time a comment in the corresponding threads is made, the thread gets pushed to the top of the feed. But I want only the thread creation posted. ([LowEndBox knows that this isn't ideal for everyone...](https://lowendbox.com/blog/how-to-monitor-new-lowendtalk-offers-with-python/)) I assume this is not the only feed with this behavior.

**Comment by Qolors** [comment]
Thanks for sharing! Do you often reset the feedcord service?

I ask this because let's say for two of the posts in the rss feed you have:

- A post on February 1st
- A post on January 28th

A new comment is made on the January 28th post today, pushing it to the top. Then let's say we run the feedcord service right after.

This will make it _a little wonky_ at first - any new comments on posts with a publish date newer than the 28th will be pushed and notified.. this is the issue you're facing I assume.

However, it will eventually work itself out when the first brand new post gets read while FeedCord is running.

Once we have that newest post's date cached, it should work as intended only showing when a newer dated post is made.

If you happen to reset the FeedCord service though, you lose that newest publishing date and that wonky cycle starts over again if an old post is at the top.

Not sure if I can update to handle this, as I built this with no persistent storage/cache except the small internal hastable holding the dates during runtime to keep lightweight.. I could possibly have a flag that will process all items in the feed rather than just the first item at the top? Have to think on it though..

If I'm missing something let me know - thanks!

**Comment by Qolors** [comment]
This will be closed for now until further information is provided
